baseurl: /
languageCode: en-us
title: 今日之森
theme: hugo-ivy
disqusShortname: 'gs'
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  post: /:year/:month/:day/:slug/
menu:
  main:
    - name: About
      url: /about
      weight: 1
    - name: 分子生物学实验原理
      url: /the-principle-of-molecular-biology
      weight: 2
    - name: 实验技能与常用技巧
      url: /skill
      weight: 3
    - name: 蛋白互作验证实验原理
      url: /protein-protein-interaction-experiment
      weight: 4
    - name: 基因家族分析
      url: /gene-family-analysis
      weight: 5
    - name: 生物信息学
      url: /bioinfomatics
      weight: 6
    - name: 基因组
      url: /genome
      weight: 7
    - name: 科学史
      url: /science-history
      weight: 8
    - name: 文献阅读
      url: /Reading
      weight: 9
    - name: 怪圈
      url: /guaiquan
      weight: 10
    - name: Linux
      url: /linux
      weight: 11
    - name: R
      url: /R
      weight: 12
    - name: 跑步
      url: /Running
      weight: 13
    - name: 随笔
      url: /informal-essay
      weight: 14
    - name: 军旅生涯
      url: /Military-career
      weight: 15

params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: 记录科研路上的点点滴滴。
  footer: "&copy; 今日之森 2020 - 2021"
  favicon: favicon.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  disqusURL: "https://academic-demo.netlify.app/"
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  logo:
    img: /content/logo.png
    url: /content/logo.png
    alt: zhaoguosen
    tag: 
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: yes
